### PR TITLE
change to fix mode for uploading

### LINKED ISSUE #79: upload will fail when I upload file to OneDrive for personal
When I use microsoft account(hotmail account) to login and upload a file, the response is 

<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>OneDrive</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>Ref A: DF585EFBED4E48E2B34BFC2A854CA55C Ref B: AB553E4C7F4A8B9273E7805B5989367C Ref C: Thu May 19 19:34:13 2016 PST</span></div></div></body></html>

### PR DESCRIPTION
**Pull request by daboxu**
fix#79

### CODE REVIEW

**Comment by peternied** [comment]
:shipit:

**Comment by peternied** [comment]
Please publish make sure to publish the new 1.2 release here and on bintray

**Comment by daboxu** [comment]
has uploaded the SDK to bintray: https://bintray.com/onedrive/Maven/onedrive-sdk-android/view
the issue #79 should be fixed

**Comment by peternied** [comment]
Please [make a new release](https://github.com/OneDrive/onedrive-sdk-android/releases/new)

**Pull request merged**
