### PR TITLE
Sdk usability improvements

### PR DESCRIPTION
**Pull request by modislaszlox2**
I did some changes sdk which I needed on the project I'm working on and I thought this changes could beneficial for others also.

Changes: 
- Silent login
- Refresh token getter
- Uploading file using InputStream
- Removing unnecessary information for the authenticator(issues with silent login)

### CODE REVIEW

**Comment by modislaszlox2** [comment]
@daboxu Please have a look.

**Comment by daboxu** [comment]
hi @modislaszlox2 , thanks for the contribution and I really appreciated that. While we are moving the OneDrive SDK to a part of [Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-android), I am a little bit worried about the large change you made. Could you try use the Graph SDK instead?

**Comment by modislaszlox2** [comment]
@daboxu the graph sdk has the same issues as one drive sdk and I don't want to modify another sdk just to make it usable. I will continue to use my fork, but it's your call if you want to merge this changes to make other dev's life easier or they have to do the same changes as I did.

**Comment by daboxu** [comment]
@modislaszlox2 thanks for the headsup, Microsoft Graph team is taking into the issue and the related one: https://github.com/OfficeDev/msa-auth-for-android/issues/34

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information

**Pull request closed without merging**
